### ISSUE TITLE
Calling the output of .map(...) because PARENTHESES

### ISSUE THREAD

**Issue by SheepTester** [RGBsec/rgbctf-frontend#20]
https://github.com/RGBsec/rgbctf-frontend/blob/1dc7a82231f5ab82e33ac1e2018a5a2dec92771f/src/App.jsx#L58-L67

Due to the brilliance of mimicking Java syntax, two adjacent parentheses in JavaScript will be interpreted as a function call using the left parentheses as a function and the right parentheses as the arguments. However, `.map(...)` does not return a function; it returns an array. So JavaScript dies

**Comment by chop0** [comment]
oh my god

**Comment by chop0** [comment]
thank you sir
